name: 🧠 Agente de Noticias Diario (demo)

on:
  schedule:
    - cron: '20 11 * * *'  # 6:20 a.m. hora CDMX (UTC-6 fijo, sin horario de verano)
  workflow_dispatch:       # Permite ejecución manual

jobs:
  ejecutar-agente:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo .env con secretos
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "GMAIL_ADDRESS=${{ secrets.GMAIL_ADDRESS }}" >> .env
          echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> .env
          echo "EMAIL_RECEIVER=${{ secrets.EMAIL_RECEIVER }}" >> .env

      - name: Ejecutar agente
        run: python main.py
